name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: rust-clippy-check
      uses: actions-rs/clippy-check@v1.0.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
